### ISSUE TITLE
destructors don't appear to be called: leaking memory & file descriptors

### ISSUE THREAD

**Issue by mkomitee** [apple/ccs-pykerberos#70] opened 2018-04-09 21:08 UTC
I'm not 100% sure why, but it looks like something is preventing `destroy_gss_server` from being called when the reference count for our context object should be collected.  Similarly, somethings fishy with the destructor on the client side of things as well.

Here's a reproducer for the server side. The evidence of the leak here is that we leak file descriptors which point to our replay caches:

    #!/usr/bin/env python

    import gc
    import kerberos
    import os

    SERVICE = 'HTTP@myexample.com'
    COUNT = 10

    def server_init():
        kerberos.authGSSServerInit(SERVICE)

    def main():
        for _ in range(COUNT):
            server_init()
        # Because I'm not entirely certain that python's gc guaranty's timeliness
        # of destructors, lets kick off a manual gc.
        gc.collect()

        dirname = os.path.join('/proc/', str(os.getpid()), 'fd')
        for fname in  os.listdir(dirname):
            try:
                target = os.readlink(os.path.join(dirname, fname))
                print("fd {} => {}".format(fname, target))
            except EnvironmentError:
                pass
        raw_input("Hit [ENTER] to continue> ")

    if __name__ == '__main__':
        main()

And when you run it, (on linux, and assuming you replace `HTTP@myexample.com` with something in your system keytab or in a keytab pointed to by `KRB5_KTNAME`), you'll see something along these lines:

    fd 0 => /dev/pts/0
    fd 1 => /dev/pts/0
    fd 2 => /dev/pts/0
    fd 3 => /var/tmp/HTTP_12345
    fd 4 => /var/tmp/HTTP_12345
    fd 5 => /var/tmp/HTTP_12345
    fd 6 => /var/tmp/HTTP_12345
    fd 7 => /var/tmp/HTTP_12345
    fd 8 => /var/tmp/HTTP_12345
    fd 9 => /var/tmp/HTTP_12345
    fd 10 => /var/tmp/HTTP_12345
    fd 11 => /dev/urandom
    fd 12 => /var/tmp/HTTP_12345
    fd 13 => /var/tmp/HTTP_12345
    fd 14 => /var/tmp/HTTP_12345
    fd 15 => /var/tmp/HTTP_12345
    fd 16 => /var/tmp/HTTP_12345
    fd 17 => /var/tmp/HTTP_12345
    fd 18 => /var/tmp/HTTP_12345
    fd 19 => /var/tmp/HTTP_12345
    fd 20 => /var/tmp/HTTP_12345
    fd 21 => /var/tmp/HTTP_12345
    fd 22 => /var/tmp/HTTP_12345
    fd 23 => /var/tmp/HTTP_12345
    Hit [ENTER] to continue>

All of those `/var/tmp/HTTP_12345` links are leaked open file descriptors for your users (the `12345` will be replaced with your `uid`) HTTP service replay cache file. If you changed `HTTP@myexample.com` to `OTHERSERVICE@otherplace.com`, they'll be temp files with `OTHERSERVICE` in the name.

I did some testing, and the same reproducer works on 2.7 & 3.6.

Here's a reproducer for the client side issue (I used psutil to check the processes memory usage):

    #!/usr/bin/env python

    import gc
    import kerberos
    import psutil

    SERVICE = 'HTTP@myexample.com'

    def client_init():
        kerberos.authGSSClientInit(SERVICE)

    def n_times(count):
        before = psutil.Process().memory_info().rss
        for _ in range(count):
            client_init()
        # Because I'm not entirely certain that python's gc guaranty's timeliness
        # of destructors, lets kick off a manual gc.
        gc.collect()
        after = psutil.Process().memory_info().rss
        delta = after - before
        print("Leaked {} total in {} calls: ~{} bytes per call".format(delta, count, delta / count))

    def main():
        n_times(1000)
        n_times(10000)
        n_times(100000)
        n_times(1000000)

    if __name__ == '__main__':
        main()

Since this is the client side, you don't need a keytab. When I run this, I get:

    Leaked 212992 total in 1000 calls: ~212 bytes per call
    Leaked 3252224 total in 10000 calls: ~325 bytes per call
    Leaked 31789056 total in 100000 calls: ~317 bytes per call
    Leaked 318693376 total in 1000000 calls: ~318 bytes per call

**Comment by rgbyrnes** [comment] 2018-04-09 21:45
I think the cause is that authGSSServerInit and authGSSClientInit call Py_BuildValue with "O", and that increments the refcount of pystate (from 1 to 2), so it will never be reclaimed, even when it goes out of scope in the caller, because the refcount will drop back to 1 (not 0).  This could be fixed by using "N" instead of "O".

There seems to be another leak in each function if (result == AUTH_GSS_ERROR) ... the functions should call Py_DECREF(pystate) before returning early.  Or (perhaps better) construct pystate later, when Py_BuildValue is called.

**Comment by behackett** [comment] 2018-04-09 22:12
Nice catch. It looks like that leak has been in ccs-pykerberos for years. It was caught and fixed in one of the forks a while ago: https://github.com/02strich/pykerberos/commit/088d4538a746f0346b46eba03998045e6c694ada

**Comment by dreness** [comment] 2018-04-10 00:35
Good detective work, and thanks for the repro cases @mkomitee! I'll get these going in the existing test harness, so I should be able to check in both the fix for the FD leak and the proof that the fix works...

**Comment by behackett** [comment] 2018-04-10 02:30
I took a look at the necessary changes. authenticate_gss_client_init and authenticate_gss_server_init both set the gss_*_state members to reasonable default values before doing anything else. The cleanest way to fix this is to change O to N, and call Py_DECREF on pystate if either of the init functions fails. The destructor will do the cleanup. It probably also makes sense to check if PyCObject_FromVoidPtr fails (pystate will be NULL) and free state if it does, before returning NULL.

**Comment by behackett** [comment] 2018-04-10 20:00
@mkomitee can you try the patch in https://github.com/apple/ccs-pykerberos/pull/71?

**Comment by mkomitee** [comment] 2018-04-10 21:25
Going to test it shortly, but if you want to test the returns from `PyCObject_FromVoidPtr` like that, you may want to do it in `channelBindings` as well. 

Not sure whether you'd want to do so in the `MOD_INIT` when you're adding `GSS_MECH_OID_{KRB5,SPEGNO}` to the module dictionary.

**Comment by rgbyrnes** [comment] 2018-04-10 21:36
Also, at the end of `channelBindings`, I think ...

`return Py_BuildValue("N", pychan_bindings);`

... could be replaced by ...

`return pychan_bindings;`

**Comment by behackett** [comment] 2018-04-10 21:46
There is a lot of error checking that could be added. I'm happy to add more as time allows, but I'm not a maintainer of this project, just a user.

**Comment by dreness** [comment] 2018-04-10 21:53
@behackett thanks for your efforts :) I'm currently messing around with running the scripts @mkomitee provided as part of the automated tests, which should lend additional confidence to the fix.

**Comment by behackett** [comment] 2018-04-11 05:15
Change range(count) to xrange(count) for Python 2. That solves the problem for me.

**Comment by mkomitee** [comment] 2018-04-11 17:01
The patch looks good to me.

I suspect the leak in 2.7 with the fix has more to do with python 2.7's range() than it has to do with kerberos:

    import psutil
    count = 10000
    for mechanism in (range, xrange):
        before = psutil.Process().memory_info().rss
        for _ in mechanism(count):
            pass
        after = psutil.Process().memory_info().rss
        print("{} leaked {} bytes per iteration".format(
            mechanism, (after - before) /  count))

whern run prints out:

    <built-in function range> leaked 27 bytes per iteration
    <type 'xrange'> leaked 0 bytes per iteration

**Comment by dreness** [comment] 2018-04-12 01:46
Cool, thanks for the tip about range / xrange. I'll make that change, add some asserts to the tests, merge and do a pypi release... soon - hopefully tomorrow.

On the topic of maintenance, I do have the authority of a maintainer, although I don't really do much maintenance on account of not really having a lot of time to spend on this project these days. However, I do generally believe in the GitHub dream and am willing to push buttons here and there to leverage the contributions of helpful and interested users.

**Comment by jmehnle** [comment] 2018-06-08 01:46
@dreness, any chance you could make that PYPI release soon? I'm really hoping [`requests-kerberos`](https://github.com/requests/requests-kerberos) can [switch](https://github.com/requests/requests-kerberos/issues/97) from the old [`pykerberos`](https://github.com/02strich/pykerberos) to [`ccs-pykerberos`](https://github.com/apple/ccs-pykerberos) once this release is out.

**Comment by omegagx** [comment] 2018-06-12 23:14
when will this be fixed in an official release?

**Comment by behackett** [comment] 2018-10-09 22:53
@dreness - ping! It would be great to get this fix into master and released.

**Comment by dreness** [comment] 2018-10-10 05:47
I've updated my fork of @behackett 's PR to finish up the test cases contributed by @mkomitee by adding asserts to check for memory or FD leaks. With the new asserts in place, if I revert the fix, the tests [fail as expected](https://travis-ci.org/dreness/ccs-pykerberos/jobs/439472301#L1303):

```
tests/test_kerberos.py::test_service_principal PASSED                    [ 16%]
tests/test_kerberos.py::test_basic_check_password PASSED                 [ 33%]
tests/test_kerberos.py::test_gssapi PASSED                               [ 50%]
tests/test_kerberos.py::test_http_endpoint PASSED                        [ 66%]
tests/test_kerberos.py::test_leaks_server_linux FAILED                   [ 83%]
tests/test_kerberos.py::test_leaks_client FAILED                         [100%]
... (elided output) ...
====================== 2 failed, 4 passed in 0.21 seconds ======================
```

... and with the fix in place, [all the tests pass](https://travis-ci.org/dreness/ccs-pykerberos/jobs/439474147#L1303):

```
tests/test_kerberos.py::test_service_principal PASSED                    [ 16%]
tests/test_kerberos.py::test_basic_check_password PASSED                 [ 33%]
tests/test_kerberos.py::test_gssapi PASSED                               [ 50%]
tests/test_kerberos.py::test_http_endpoint PASSED                        [ 66%]
tests/test_kerberos.py::test_leaks_server_linux PASSED                   [ 83%]
tests/test_kerberos.py::test_leaks_client PASSED                         [100%]
=========================== 6 passed in 1.08 seconds ===========================
```

I think this is ready to go, although I wouldn't complain if anyone wanted to glance at [my fork](https://github.com/apple/ccs-pykerberos/compare/master...dreness:master) as a final sanity check before release.

**Comment by belyaev-pa** [comment] 2018-11-15 12:44
guys this fix breaks authGSSServerStoreDelegate() this always return NULL after any forks or patch injected

**Closed** 2019-04-11 23:19 UTC

**Comment by stphnlyd** [comment] 2019-08-23 09:38
@dreness Could you release this to PyPI? Latest on PyPI is still 1.3.0
